# Build stage
FROM golang:1.24-alpine AS builder

WORKDIR /app

RUN apk add --no-cache git

COPY go.mod go.sum* ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /client ./cmd/client

FROM alpine:latest

WORKDIR /app

COPY --from=builder /client .

# COPY --from=builder /app/static ./static

# Expose HTTP port
EXPOSE 8080

# Run the client
CMD ["./client"]