// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func DeployForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"max-w-md bg-gray-800 p-6 rounded-lg shadow-lg mx-auto mt-10\"><h2 class=\"text-lg mb-4 font-semibold\">Iniciar Robô</h2><form hx-post=\"/bots/run\" hx-ext=\"json-enc\" hx-target=\"#log-container\" hx-swap=\"innerHTML\" class=\"space-y-4\"><div><label class=\"block text-sm text-gray-400\">Bot ID</label> <input name=\"bot_id\" type=\"text\" class=\"w-full bg-gray-700 border-none rounded p-2 mt-1\" placeholder=\"ex: rpa-01\"></div><div><label class=\"block text-sm text-gray-400\">Git Repo</label> <input name=\"git_repo\" type=\"text\" class=\"w-full bg-gray-700 border-none rounded p-2 mt-1\" placeholder=\"https://github.com/...\"></div><div><label class=\"block text-sm text-gray-400\">Versão</label> <input name=\"version\" type=\"text\" class=\"w-full bg-gray-700 border-none rounded p-2 mt-1\" placeholder=\"1.0.0\"></div><button type=\"submit\" class=\"w-full bg-blue-600 hover:bg-blue-500 py-2 rounded font-bold transition\">rodar o bot 🚀</button></form><div hx-ext=\"sse\" sse-connect=\"/bots/run\" sse-swap=\"message\" class=\"bg-black p-4 h-64 overflow-y-auto\"><div id=\"log-container\" class=\"mt-6 p-4 bg-black rounded text-green-500 font-mono text-sm h-64 overflow-y-auto\">Aguardando comando...</div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
